spring:
  webflux:
    urlpatterns:
      - "/**"
    hiddenmethod:
      filter:
        enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    com.example: DEBUG